version: '3.7'
services:
  redis:
    image: redis:5-alpine
  queue:
    image: node:alpine
    command: node main.js
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    depends_on:
      - redis
